name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run npm audit
      run: npm audit --production || echo "Security vulnerabilities found"
    
    - name: Run pip safety check
      run: |
        python -m pip install --upgrade pip
        pip install safety
        if [ -f requirements.txt ]; then
          safety check -r requirements.txt || echo "Security vulnerabilities found"
        else
          echo "No requirements.txt file found"
        fi
